version: '3'
services:
  postgres:
    image: postgres:11-alpine
    environment:
      - "POSTGRES_DB=helse-spenn-oppdrag"
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=postgres"
    ports:
      - "5432:5432"
  flyway:
    image: boxfuse/flyway:5-alpine
    entrypoint: []
    command: ["/spenn/wait_for.sh", "postgres:5432","/flyway/flyway -url=jdbc:postgresql://postgres:5432/helse-spenn-oppdrag -schemas=public -user=postgres -password=postgres migrate"]
    volumes:
      - ./src/main/resources/db/migration:/flyway/sql
      - ./compose/spenn:/spenn
    depends_on:
      - postgres

