apiVersion: batch/v1
kind: Job
metadata:
  labels:
    team: tbd
  name: spoler
  namespace: tbd
spec:
  ttlSecondsAfterFinished: 300
  backoffLimit: 1
  template:
    metadata:
      labels:
        team: tbd
    spec:
      containers:
        - name: spoler
          image: {{image}}
          resources:
            requests:
              memory: 256Mi
              cpu: 100m
            limits:
              memory: 512Mi
              cpu: 500m
          volumeMounts:
            - mountPath: /var/run/secrets/nais.io/kafka
              name: kafka-credentials
              readOnly: true
          env:
            - name: KAFKA_BROKERS
              valueFrom:
                secretKeyRef:
                  key: KAFKA_BROKERS
                  name: kafka-spoler-nav-dev-manuelt-opprettet
            - name: KAFKA_CREDSTORE_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: KAFKA_CREDSTORE_PASSWORD
                  name: kafka-spoler-nav-dev-manuelt-opprettet
            - name: KAFKA_KEYSTORE_PATH
              value: /var/run/secrets/nais.io/kafka/client.keystore.p12
            - name: KAFKA_TRUSTSTORE_PATH
              value: /var/run/secrets/nais.io/kafka/client.truststore.jks
      imagePullSecrets:
        - name: gpr-credentials
      serviceAccount: podcreator
      serviceAccountName: podcreator
      volumes:
        - name: kafka-credentials
          secret:
            defaultMode: 420
            items:
              - key: KAFKA_CERTIFICATE
                path: kafka.crt
              - key: KAFKA_PRIVATE_KEY
                path: kafka.key
              - key: KAFKA_CA
                path: ca.crt
              - key: client.keystore.p12
                path: client.keystore.p12
              - key: client.truststore.jks
                path: client.truststore.jks
            secretName: kafka-spoler-nav-dev-manuelt-opprettet
      restartPolicy: Never

