apiVersion: batch/v1
kind: Job
metadata:
  labels:
    team: tbd
  name: spoler
  namespace: tbd
spec:
  ttlSecondsAfterFinished: 300
  backoffLimit: 1
  template:
    spec:
      containers:
        - name: spoler
          image: {{image}}
          resources:
            requests:
              memory: 256Mi
              cpu: 100m
            limits:
              memory: 512Mi
              cpu: 500m
          volumeMounts:
            - mountPath: /var/run/secrets/nais.io/vault #kan denne fjernes ettersom vi ikke har database?
              name: vault-secrets
              subPath: subpath/var/run/secrets/nais.io/vault
            - mountPath: /var/run/secrets/nais.io/kafka
              name: kafka-credentials
              readOnly: true
          env:
            - name: VAULT_TOKEN_PATH
              value: /var/run/secrets/nais.io/vault/vault_token
            - name: KAFKA_RAPID_TOPIC  #kan denne fjernes ettersom vi setter topic i hvert case?
              value: tbd.rapid.v1
            - name: KAFKA_BROKERS
              valueFrom:
                secretKeyRef:
                  key: KAFKA_BROKERS
                  name: kafka-spoler-nav-dev-manuelt-opprettet
            - name: KAFKA_CREDSTORE_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: KAFKA_CREDSTORE_PASSWORD
                  name: kafka-spoler-nav-dev-manuelt-opprettet
            - name: KAFKA_KEYSTORE_PATH
              value: /var/run/secrets/nais.io/kafka/client.keystore.p12
            - name: KAFKA_TRUSTSTORE_PATH
              value: /var/run/secrets/nais.io/kafka/client.truststore.jks
      imagePullSecrets:
        - name: gpr-credentials
      initContainers:
        - name: vks-init
          image: navikt/vault-sidekick:v0.3.10-d122b16
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "1000m"
          volumeMounts:
            - mountPath: /var/run/secrets/nais.io/vault #kan denne fjernes ettersom vi ikke har database?
              name: vault-secrets
              subPath: subpath/var/run/secrets/nais.io/vault
          args:
            - -v=10
            - -logtostderr
            - -vault=https://vault.adeo.no #kan denne fjernes ettersom vi ikke har database?
            - -one-shot
            - -save-token=/var/run/secrets/nais.io/vault/vault_token #kan vault fjernes ettersom vi ikke har database?
          env:
            - name: VAULT_AUTH_METHOD #kan vault fjernes ettersom vi ikke har database?
              value: kubernetes
            - name: VAULT_SIDEKICK_ROLE
              value: spoler
            - name: VAULT_K8S_LOGIN_PATH
              value: auth/kubernetes/preprod/fss/login
      serviceAccount: podcreator
      serviceAccountName: podcreator
      volumes:
        - name: vault-secrets
          emptyDir:
            medium: Memory
        - name: kafka-credentials
              secret:
                  defaultMode: 420
                  items:
                      - key: KAFKA_CERTIFICATE
                        path: kafka.crt
                      - key: KAFKA_PRIVATE_KEY
                        path: kafka.key
                      - key: KAFKA_CA
                        path: ca.crt
                      - key: client.keystore.p12
                        path: client.keystore.p12
                      - key: client.truststore.jks
                        path: client.truststore.jks
                  secretName: kafka-spoler-nav-dev-manuelt-opprettet
      restartPolicy: Never

